export enum ActionTypes {
  KEYDOWN,
  KEYUP,
  UPDATE,
  SPAWN_BULLET,
  SPAWN_ENEMY,
  SPAWN_EXPLOSION,
  ENEMY_RECEIVES_BULLET,
  AXIS_X_CHANGE,
  AXIS_Y_CHANGE,
  PIEUWER_COLLIDES,
  ENEMY_COLLIDES_WITH_PIEUWER
}
